use crate::errors::ErrorCode;
use crate::events::TemporaryWalletFunded;
use crate::states::{DeployRequest, DeployRequestStatus, TreasuryPool};
use anchor_lang::prelude::*;

/// Fund a temporary wallet for deployment
/// Only backend admin can call this instruction
/// The temporary wallet is generated by backend and not known to developer
#[derive(Accounts)]
#[instruction(request_id: [u8; 32])]
pub struct FundTemporaryWallet<'info> {
    #[account(
        mut,
        seeds = [TreasuryPool::PREFIX_SEED],
        bump = treasury_pool.bump
    )]
    pub treasury_pool: Account<'info, TreasuryPool>,

    #[account(
        mut,
        seeds = [DeployRequest::PREFIX_SEED, request_id.as_ref()],
        bump = deploy_request.bump,
        constraint = deploy_request.status == DeployRequestStatus::PendingDeployment @ ErrorCode::InvalidDeploymentStatus
    )]
    pub deploy_request: Account<'info, DeployRequest>,

    #[account(
        mut,
        constraint = admin.key() == treasury_pool.admin @ ErrorCode::Unauthorized
    )]
    pub admin: Signer<'info>,

    /// CHECK: Temporary wallet generated by backend
    #[account(mut)]
    pub temporary_wallet: UncheckedAccount<'info>,
}

pub fn fund_temporary_wallet(
    ctx: Context<FundTemporaryWallet>,
    _request_id: [u8; 32],
    amount: u64,
) -> Result<()> {
    let treasury_pool = &mut ctx.accounts.treasury_pool;
    let deploy_request = &mut ctx.accounts.deploy_request;

    require!(!treasury_pool.emergency_pause, ErrorCode::ProgramPaused);
    require!(amount > 0, ErrorCode::InvalidAmount);
    require!(
        treasury_pool.total_staked >= amount,
        ErrorCode::InsufficientTreasuryFunds
    );

    // Verify that the requested amount matches the deployment cost in deploy_request
    require!(
        amount == deploy_request.deployment_cost,
        ErrorCode::InvalidAmount
    );

    // Transfer SOL from Treasury Pool PDA to temporary wallet via lamport mutation
    let treasury_pool_info = treasury_pool.to_account_info();
    let temporary_wallet_info = ctx.accounts.temporary_wallet.to_account_info();

    {
        let mut treasury_lamports = treasury_pool_info.try_borrow_mut_lamports()?;
        let mut temporary_lamports = temporary_wallet_info.try_borrow_mut_lamports()?;

        require!(**treasury_lamports >= amount, ErrorCode::InsufficientTreasuryFunds);

        let new_treasury_balance = (**treasury_lamports)
            .checked_sub(amount)
            .ok_or(ErrorCode::CalculationOverflow)?;
        let new_temporary_balance = (**temporary_lamports)
            .checked_add(amount)
            .ok_or(ErrorCode::CalculationOverflow)?;

        **treasury_lamports = new_treasury_balance;
        **temporary_lamports = new_temporary_balance;
    }

    // Update treasury pool
    treasury_pool.total_staked = treasury_pool
        .total_staked
        .checked_sub(amount)
        .ok_or(ErrorCode::CalculationOverflow)?;

    // Store temporary wallet address in deploy_request
    deploy_request.ephemeral_key = Some(temporary_wallet_info.key());

    emit!(TemporaryWalletFunded {
        request_id: deploy_request.request_id,
        temporary_wallet: temporary_wallet_info.key(),
        amount,
        funded_at: Clock::get()?.unix_timestamp,
    });

    Ok(())
}

